baseurl = "http://joeandmel.github.io/"
languageCode = "en-us"
title = "jam - comfort food for vegans"
theme = "casper"

paginate = 5
# DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2015"
# canonifyurls = true

[params]
  description = "find amazing recipes"
  cover = "images/cover.jpg"
  logo = "images/logo.png"
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  # githubName = "vjeantet"
  # twitterName = "vjeantet"
  # facebookName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
